name: Continuous Integration
on: push
env:
  DB_NAME: "test"
  DB_USER: "root"
  DB_PASSWORD: "Abcd@1234"
  DB_HOST: "localhost"
  DB_PORT: "3306"
jobs:
  run_code_checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Up MySQL
        run: |
          sudo /etc/init.d/mysql start
          echo "service started"
          sudo mysql -uroot -proot -e "ALTER USER '${{env.DB_USER}}'@'${{env.DB_HOST}}' IDENTIFIED BY '${{env.DB_PASSWORD}}';"
          echo "password changed"
          sudo mysql -u${{env.DB_USER}} -p${{env.DB_PASSWORD}} -e "CREATE DATABASE ${{env.DB_NAME}};"

      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run test
        run: |
          go test